name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # or your target version

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Docker build
      run: docker build -t transactiontask-app .